import { VerticalBox } from "std-widgets.slint";
import { Game } from "base.slint";


component Byte {
    in-out property <bool> activated;
    in-out property <bool> selected;
    in property <image> source;
    in property <int> selected-count;

    callback activate(bool);
    callback select(bool);

    Rectangle {
        background: Colors.blue;
        border-radius: 15px;
        visible: selected;
    }

    Image {
        opacity: activated ? 1.0 : 0.3;
        source: root.source;
        image-fit: ImageFit.contain;
    }

    TouchArea {
        pointer-event(event) => {
            if event.kind == PointerEventKind.down {
                if event.button == PointerEventButton.left {
                    if root.activated == true && root.selected == true {
                        select(false);
                    }
                    activate(!root.activated);
                }
                else if event.button == PointerEventButton.right {
                    if (selected-count < 4 || root.selected == true) && root.activated {
                        select(!root.selected);
                    }
                }
            }
        }
    }

    @children
}

export component BytesScreen {
    in-out property <[bool]> bytes: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];
    property <[bool]> selected: [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];
    property <int> selected-count;
    in property <Game> game;

    callback byte-edited(int, bool);
    callback byte-selected-edited(int, bool);
    callback set-selected-bytes([bool], int);


    set-selected-bytes(selected, count) => {
        root.selected = selected;
        root.selected-count = count;
    }

    VerticalBox {
        spacing: 10px;

        Text {
            text: "Bytes";
            font-size: 28px;
            horizontal-alignment: center;
            vertical-alignment: center;
        }            


        if root.game == Game.WorldVanilla: GridLayout {
            spacing: 1px;
            min-height: c.preferred-height * 3 + 2px;
            min-width: c.preferred-width * 7 + 6px;

            c := Byte {
                col: 0;
                row: 0;

                activated: bytes[0];
                selected: selected[0];
                source: @image-url("assets/bytes/1.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[0] = b;
                    byte-edited(0, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[0] = b;
                        byte-selected-edited(0, b);
                    }   
                }
            }
            Byte {
                col: 1;
                row: 0;

                activated: bytes[1];
                selected: selected[1];
                source: @image-url("assets/bytes/2.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[1] = b;
                    byte-edited(1, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[1] = b;
                        byte-selected-edited(1, b);
                    }   
                }
            }
            Byte {
                col: 2;
                row: 0;

                activated: bytes[2];
                selected: selected[2];
                source: @image-url("assets/bytes/3.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[2] = b;
                    byte-edited(2, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[2] = b;
                        byte-selected-edited(2, b);
                    }   
                }
            }
            Byte {
                col: 3;
                row: 0;

                activated: bytes[3];
                selected: selected[3];
                source: @image-url("assets/bytes/4.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[3] = b;
                    byte-edited(3, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[3] = b;
                        byte-selected-edited(3, b);
                    }   
                }
            }
            Byte {
                col: 4;
                row: 0;

                activated: bytes[4];
                selected: selected[4];
                source: @image-url("assets/bytes/5.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[4] = b;
                    byte-edited(4, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[4] = b;
                        byte-selected-edited(4, b);
                    }   
                }
            }
            Byte {
                col: 5;
                row: 0;

                activated: bytes[5];
                selected: selected[5];
                source: @image-url("assets/bytes/6.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[5] = b;
                    byte-edited(5, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[5] = b;
                        byte-selected-edited(5, b);
                    }   
                }
            }
            Byte {
                col: 6;
                row: 0;

                activated: bytes[6];
                selected: selected[6];
                source: @image-url("assets/bytes/7.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[6] = b;
                    byte-edited(6, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[6] = b;
                        byte-selected-edited(6, b);
                    }   
                }
            }
            Byte {
                col: 0;
                row: 1;

                activated: bytes[7];
                selected: selected[7];
                source: @image-url("assets/bytes/8.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[7] = b;
                    byte-edited(7, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[7] = b;
                        byte-selected-edited(7, b);
                    }   
                }
            }
            Byte {
                col: 1;
                row: 1;

                activated: bytes[8];
                selected: selected[8];
                source: @image-url("assets/bytes/9.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[8] = b;
                    byte-edited(8, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[8] = b;
                        byte-selected-edited(8, b);
                    }   
                }
            }
            Byte {
                col: 2;
                row: 1;

                activated: bytes[9];
                selected: selected[9];
                source: @image-url("assets/bytes/10.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[9] = b;
                    byte-edited(9, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[9] = b;
                        byte-selected-edited(9, b);
                    }   
                }
            }
            Byte {
                col: 3;
                row: 1;

                activated: bytes[10];
                selected: selected[10];
                source: @image-url("assets/bytes/11.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[10] = b;
                    byte-edited(10, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[10] = b;
                        byte-selected-edited(10, b);
                    }   
                }
            }
            Byte {
                col: 4;
                row: 1;

                activated: bytes[11];
                selected: selected[11];
                source: @image-url("assets/bytes/12.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[11] = b;
                    byte-edited(11, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[11] = b;
                        byte-selected-edited(11, b);
                    }   
                }
            }
            Byte {
                col: 5;
                row: 1;

                activated: bytes[12];
                selected: selected[12];
                source: @image-url("assets/bytes/13.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[12] = b;
                    byte-edited(12, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[12] = b;
                        byte-selected-edited(12, b);
                    }   
                }
            }
            Byte {
                col: 6;
                row: 1;

                activated: bytes[13];
                selected: selected[13];
                source: @image-url("assets/bytes/14.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[13] = b;
                    byte-edited(13, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[13] = b;
                        byte-selected-edited(13, b);
                    }   
                }
            }
            Byte {
                col: 0;
                row: 2;

                activated: bytes[14];
                selected: selected[14];
                source: @image-url("assets/bytes/15.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[14] = b;
                    byte-edited(14, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[14] = b;
                        byte-selected-edited(14, b);
                    }   
                }
            }
            Byte {
                col: 1;
                row: 2;

                activated: bytes[15];
                selected: selected[15];
                source: @image-url("assets/bytes/16.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[15] = b;
                    byte-edited(15, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[15] = b;
                        byte-selected-edited(15, b);
                    }   
                }
            }
            Byte {
                col: 2;
                row: 2;

                activated: bytes[16];
                selected: selected[16];
                source: @image-url("assets/bytes/17.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[16] = b;
                    byte-edited(16, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[16] = b;
                        byte-selected-edited(16, b);
                    }   
                }
            }
            Byte {
                col: 3;
                row: 2;

                activated: bytes[17];
                selected: selected[17];
                source: @image-url("assets/bytes/18.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[17] = b;
                    byte-edited(17, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[17] = b;
                        byte-selected-edited(17, b);
                    }   
                }
            }
            Byte {
                col: 4;
                row: 2;

                activated: bytes[18];
                selected: selected[18];
                source: @image-url("assets/bytes/19.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[18] = b;
                    byte-edited(18, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[18] = b;
                        byte-selected-edited(18, b);
                    }   
                }
            }
            Byte {
                col: 5;
                row: 2;

                activated: bytes[19];
                selected: selected[19];
                source: @image-url("assets/bytes/20.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[19] = b;
                    byte-edited(19, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[19] = b;
                        byte-selected-edited(19, b);
                    }   
                }
            }
            Byte {
                col: 6;
                row: 2;

                activated: bytes[20];
                selected: selected[20];
                source: @image-url("assets/bytes/21.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[20] = b;
                    byte-edited(20, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[20] = b;
                        byte-selected-edited(20, b);
                    }   
                }
            }
        }

        if root.game == Game.WorldRefreshed: GridLayout {
            spacing: 1px;
            min-height: cr.preferred-height * 3 + 2px;
            min-width: cr.preferred-width * 7 + 6px;

            cr := Byte {
                col: 0;
                row: 0;

                activated: bytes[0];
                selected: selected[0];
                source: @image-url("assets/bytes/1.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[0] = b;
                    byte-edited(0, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[0] = b;
                        byte-selected-edited(0, b);
                    }   
                }
            }
            Byte {
                col: 1;
                row: 0;

                activated: bytes[1];
                selected: selected[1];
                source: @image-url("assets/bytes/2.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[1] = b;
                    byte-edited(1, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[1] = b;
                        byte-selected-edited(1, b);
                    }   
                }
            }
            Byte {
                col: 2;
                row: 0;

                activated: bytes[2];
                selected: selected[2];
                source: @image-url("assets/bytes/3.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[2] = b;
                    byte-edited(2, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[2] = b;
                        byte-selected-edited(2, b);
                    }   
                }
            }
            Byte {
                col: 3;
                row: 0;

                activated: bytes[3];
                selected: selected[3];
                source: @image-url("assets/bytes/4.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[3] = b;
                    byte-edited(3, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[3] = b;
                        byte-selected-edited(3, b);
                    }   
                }
            }
            Byte {
                col: 4;
                row: 0;

                activated: bytes[4];
                selected: selected[4];
                source: @image-url("assets/bytes/5.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[4] = b;
                    byte-edited(4, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[4] = b;
                        byte-selected-edited(4, b);
                    }   
                }
            }
            Byte {
                col: 5;
                row: 0;

                activated: bytes[5];
                selected: selected[5];
                source: @image-url("assets/bytes/6.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[5] = b;
                    byte-edited(5, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[5] = b;
                        byte-selected-edited(5, b);
                    }   
                }
            }
            Byte {
                col: 6;
                row: 0;

                activated: bytes[6];
                selected: selected[6];
                source: @image-url("assets/bytes/7.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[6] = b;
                    byte-edited(6, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[6] = b;
                        byte-selected-edited(6, b);
                    }   
                }
            }
            Byte {
                col: 0;
                row: 1;

                activated: bytes[7];
                selected: selected[7];
                source: @image-url("assets/bytes/8.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[7] = b;
                    byte-edited(7, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[7] = b;
                        byte-selected-edited(7, b);
                    }   
                }
            }
            Byte {
                col: 1;
                row: 1;

                activated: bytes[8];
                selected: selected[8];
                source: @image-url("assets/bytes/9.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[8] = b;
                    byte-edited(8, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[8] = b;
                        byte-selected-edited(8, b);
                    }   
                }
            }
            Byte {
                col: 2;
                row: 1;

                activated: bytes[9];
                selected: selected[9];
                source: @image-url("assets/bytes/10.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[9] = b;
                    byte-edited(9, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[9] = b;
                        byte-selected-edited(9, b);
                    }   
                }
            }
            Byte {
                col: 3;
                row: 1;

                activated: bytes[10];
                selected: selected[10];
                source: @image-url("assets/bytes/11.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[10] = b;
                    byte-edited(10, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[10] = b;
                        byte-selected-edited(10, b);
                    }   
                }
            }
            Byte {
                col: 4;
                row: 1;

                activated: bytes[11];
                selected: selected[11];
                source: @image-url("assets/bytes/12.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[11] = b;
                    byte-edited(11, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[11] = b;
                        byte-selected-edited(11, b);
                    }   
                }
            }
            Byte {
                col: 5;
                row: 1;

                activated: bytes[12];
                selected: selected[12];
                source: @image-url("assets/bytes/13.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[12] = b;
                    byte-edited(12, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[12] = b;
                        byte-selected-edited(12, b);
                    }   
                }
            }
            Byte {
                col: 6;
                row: 1;

                activated: bytes[13];
                selected: selected[13];
                source: @image-url("assets/bytes/14.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[13] = b;
                    byte-edited(13, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[13] = b;
                        byte-selected-edited(13, b);
                    }   
                }
            }
            Byte {
                col: 0;
                row: 2;

                activated: bytes[14];
                selected: selected[14];
                source: @image-url("assets/bytes/15.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[14] = b;
                    byte-edited(14, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[14] = b;
                        byte-selected-edited(14, b);
                    }   
                }
            }
            Byte {
                col: 1;
                row: 2;

                activated: bytes[15];
                selected: selected[15];
                source: @image-url("assets/bytes/16.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[15] = b;
                    byte-edited(15, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[15] = b;
                        byte-selected-edited(15, b);
                    }   
                }
            }
            Byte {
                col: 2;
                row: 2;

                activated: bytes[16];
                selected: selected[16];
                source: @image-url("assets/bytes/17.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[16] = b;
                    byte-edited(16, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[16] = b;
                        byte-selected-edited(16, b);
                    }   
                }
            }
            Byte {
                col: 3;
                row: 2;

                activated: bytes[17];
                selected: selected[17];
                source: @image-url("assets/bytes/18.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[17] = b;
                    byte-edited(17, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[17] = b;
                        byte-selected-edited(17, b);
                    }   
                }
            }
            Byte {
                col: 4;
                row: 2;

                activated: bytes[18];
                selected: selected[18];
                source: @image-url("assets/bytes/19.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[18] = b;
                    byte-edited(18, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[18] = b;
                        byte-selected-edited(18, b);
                    }   
                }
            }
            Byte {
                col: 5;
                row: 2;

                activated: bytes[19];
                selected: selected[19];
                source: @image-url("assets/bytes/20.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[19] = b;
                    byte-edited(19, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[19] = b;
                        byte-selected-edited(19, b);
                    }   
                }
            }
            Byte {
                col: 6;
                row: 2;

                activated: bytes[20];
                selected: selected[20];
                source: @image-url("assets/bytes/21.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[20] = b;
                    byte-edited(20, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[20] = b;
                        byte-selected-edited(20, b);
                    }   
                }
            }
            Byte {
                col: 0;
                row: 3;

                activated: bytes[21];
                selected: selected[21];
                source: @image-url("assets/bytes/22.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[21] = b;
                    byte-edited(21, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[21] = b;
                        byte-selected-edited(21, b);
                    }   
                }
            }
            Byte {
                col: 1;
                row: 3;

                activated: bytes[22];
                selected: selected[22];
                source: @image-url("assets/bytes/23.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[22] = b;
                    byte-edited(22, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[22] = b;
                        byte-selected-edited(22, b);
                    }   
                }
            }
            Byte {
                col: 2;
                row: 3;

                activated: bytes[23];
                selected: selected[23];
                source: @image-url("assets/bytes/24.png");
                selected-count: root.selected-count;

                activate(b) => {
                    root.bytes[23] = b;
                    byte-edited(23, b)
                }
                select(b) => {
                    if b {
                        root.selected-count += 1;
                    }
                    else {
                        root.selected-count -= 1;
                    }
                    if selected-count <= 4 {
                        root.selected[23] = b;
                        byte-selected-edited(23, b);
                    }   
                }
            }
        }

        Text {
            text: "Left click to add or remove byte. Right click to equip or unequip it";
            horizontal-alignment: center;
        }
    }
}