import { ImageAnim } from "base.slint";
import { SpinBox } from "std-widgets.slint";

export struct Character {
    activated: bool,
    lvl: int,
    next: int,
}

component Avatar {
    in property <int> id;
    in property <image> avatar;
    in property <image> avatar-gray;

    callback select(int);
    callback change-state(int);
    callback enter(int);

    out property <bool> has-hover: false;
    in property <int> selected-id: 0;
    in-out property <bool> activated: false;
    Image {
        source: activated ? avatar : avatar-gray;
    }

    ta := TouchArea {
        clicked => {
            select(root.id)
        }
        double-clicked => {
            change-state(root.id);
            // root.activated = !root.activated;
            if root.activated {
                enter(id);
            }
            else {
                select(0)
            }
        }
        changed has-hover => {
            if root.has-hover != ta.has-hover && root.has-hover == false {
                root.has-hover = true;
                enter(root.id);
            }
            if root.has-hover != ta.has-hover && root.has-hover == true {
                root.has-hover = false;
            }
        }
    }

    outline := Rectangle {
        visible: root.selected-id == root.id;
        border-width: 2px;
        border-color: Colors.yellow;
    }
}

export component PartyScreen {
    // property <[[image]]> characters-frames: [
    //     [],
    //     [@image-url("assets/char_animations/1/5076.png"), @image-url("assets/char_animations/1/5077.png"), @image-url("assets/char_animations/1/5080.png"), @image-url("assets/char_animations/1/5081.png"), @image-url("assets/char_animations/1/5082.png"), @image-url("assets/char_animations/1/5083.png"), @image-url("assets/char_animations/1/5084.png"), @image-url("assets/char_animations/1/5085.png"), @image-url("assets/char_animations/1/5086.png"), @image-url("assets/char_animations/1/5087.png")],
    //     [@image-url("assets/char_animations/2/8210.png"), @image-url("assets/char_animations/2/8211.png"), @image-url("assets/char_animations/2/8212.png"), @image-url("assets/char_animations/2/8213.png"), @image-url("assets/char_animations/2/8214.png"), @image-url("assets/char_animations/2/8215.png"), @image-url("assets/char_animations/2/8216.png"), @image-url("assets/char_animations/2/8217.png"), @image-url("assets/char_animations/2/8218.png"), @image-url("assets/char_animations/2/8219.png"), @image-url("assets/char_animations/2/8220.png")],        
    //     [@image-url("assets/char_animations/3/8221.png"), @image-url("assets/char_animations/3/8222.png"), @image-url("assets/char_animations/3/8223.png"), @image-url("assets/char_animations/3/8224.png"), @image-url("assets/char_animations/3/8225.png"), @image-url("assets/char_animations/3/8226.png"), @image-url("assets/char_animations/3/8227.png"), @image-url("assets/char_animations/3/8228.png"), @image-url("assets/char_animations/3/8229.png"), @image-url("assets/char_animations/3/8230.png"), @image-url("assets/char_animations/3/8231.png")],        
    //     [@image-url("assets/char_animations/4/8232.png"), @image-url("assets/char_animations/4/8233.png"), @image-url("assets/char_animations/4/8234.png"), @image-url("assets/char_animations/4/8235.png"), @image-url("assets/char_animations/4/8236.png"), @image-url("assets/char_animations/4/8237.png"), @image-url("assets/char_animations/4/8238.png"), @image-url("assets/char_animations/4/8239.png"), @image-url("assets/char_animations/4/8240.png"), @image-url("assets/char_animations/4/8241.png"), @image-url("assets/char_animations/4/8242.png")],        
    //     [@image-url("assets/char_animations/5/8243.png"), @image-url("assets/char_animations/5/8244.png"), @image-url("assets/char_animations/5/8245.png"), @image-url("assets/char_animations/5/8246.png"), @image-url("assets/char_animations/5/8247.png"), @image-url("assets/char_animations/5/8248.png"), @image-url("assets/char_animations/5/8249.png"), @image-url("assets/char_animations/5/8250.png"), @image-url("assets/char_animations/5/8251.png"), @image-url("assets/char_animations/5/8252.png"), @image-url("assets/char_animations/5/8253.png")],        
    //     [@image-url("assets/char_animations/6/8254.png"), @image-url("assets/char_animations/6/8255.png"), @image-url("assets/char_animations/6/8256.png"), @image-url("assets/char_animations/6/8257.png"), @image-url("assets/char_animations/6/8258.png"), @image-url("assets/char_animations/6/8259.png"), @image-url("assets/char_animations/6/8260.png"), @image-url("assets/char_animations/6/8261.png"), @image-url("assets/char_animations/6/8262.png"), @image-url("assets/char_animations/6/8263.png"), @image-url("assets/char_animations/6/8264.png")],        
    //     [@image-url("assets/char_animations/7/8265.png"), @image-url("assets/char_animations/7/8266.png"), @image-url("assets/char_animations/7/8267.png"), @image-url("assets/char_animations/7/8268.png"), @image-url("assets/char_animations/7/8269.png"), @image-url("assets/char_animations/7/8270.png"), @image-url("assets/char_animations/7/8271.png"), @image-url("assets/char_animations/7/8272.png"), @image-url("assets/char_animations/7/8273.png"), @image-url("assets/char_animations/7/8274.png"), @image-url("assets/char_animations/7/8275.png")],        
    //     [@image-url("assets/char_animations/8/8276.png"), @image-url("assets/char_animations/8/8277.png"), @image-url("assets/char_animations/8/8278.png"), @image-url("assets/char_animations/8/8279.png"), @image-url("assets/char_animations/8/8280.png"), @image-url("assets/char_animations/8/8281.png"), @image-url("assets/char_animations/8/8282.png"), @image-url("assets/char_animations/8/8283.png"), @image-url("assets/char_animations/8/8284.png"), @image-url("assets/char_animations/8/8285.png"), @image-url("assets/char_animations/8/8286.png")],        
    //     [@image-url("assets/char_animations/9/8287.png"), @image-url("assets/char_animations/9/8288.png"), @image-url("assets/char_animations/9/8289.png"), @image-url("assets/char_animations/9/8290.png"), @image-url("assets/char_animations/9/8291.png"), @image-url("assets/char_animations/9/8292.png"), @image-url("assets/char_animations/9/8293.png"), @image-url("assets/char_animations/9/8294.png"), @image-url("assets/char_animations/9/8295.png"), @image-url("assets/char_animations/9/8296.png"), @image-url("assets/char_animations/9/8297.png")],
    //     [@image-url("assets/char_animations/10/8298.png"), @image-url("assets/char_animations/10/8299.png"), @image-url("assets/char_animations/10/8300.png"), @image-url("assets/char_animations/10/8301.png"), @image-url("assets/char_animations/10/8302.png"), @image-url("assets/char_animations/10/8303.png"), @image-url("assets/char_animations/10/8304.png"), @image-url("assets/char_animations/10/8305.png"), @image-url("assets/char_animations/10/8306.png"), @image-url("assets/char_animations/10/8307.png"), @image-url("assets/char_animations/10/8308.png")],
    //     [@image-url("assets/char_animations/11/8309.png"), @image-url("assets/char_animations/11/8310.png"), @image-url("assets/char_animations/11/8311.png"), @image-url("assets/char_animations/11/8312.png"), @image-url("assets/char_animations/11/8313.png"), @image-url("assets/char_animations/11/8314.png"), @image-url("assets/char_animations/11/8315.png"), @image-url("assets/char_animations/11/8316.png"), @image-url("assets/char_animations/11/8317.png"), @image-url("assets/char_animations/11/8318.png"), @image-url("assets/char_animations/11/8319.png")],
    //     [@image-url("assets/char_animations/12/8320.png"), @image-url("assets/char_animations/12/8321.png"), @image-url("assets/char_animations/12/8322.png"), @image-url("assets/char_animations/12/8323.png"), @image-url("assets/char_animations/12/8324.png"), @image-url("assets/char_animations/12/8325.png"), @image-url("assets/char_animations/12/8326.png"), @image-url("assets/char_animations/12/8327.png"), @image-url("assets/char_animations/12/8328.png"), @image-url("assets/char_animations/12/8329.png"), @image-url("assets/char_animations/12/8330.png")],
    //     [@image-url("assets/char_animations/13/8331.png"), @image-url("assets/char_animations/13/8332.png"), @image-url("assets/char_animations/13/8333.png"), @image-url("assets/char_animations/13/8334.png"), @image-url("assets/char_animations/13/8335.png"), @image-url("assets/char_animations/13/8336.png"), @image-url("assets/char_animations/13/8337.png"), @image-url("assets/char_animations/13/8338.png"), @image-url("assets/char_animations/13/8339.png"), @image-url("assets/char_animations/13/8340.png")],
    //     [@image-url("assets/char_animations/14/8341.png"), @image-url("assets/char_animations/14/8342.png"), @image-url("assets/char_animations/14/8343.png"), @image-url("assets/char_animations/14/8344.png"), @image-url("assets/char_animations/14/8345.png"), @image-url("assets/char_animations/14/8346.png"), @image-url("assets/char_animations/14/8347.png"), @image-url("assets/char_animations/14/8348.png"), @image-url("assets/char_animations/14/8349.png"), @image-url("assets/char_animations/14/8350.png"), @image-url("assets/char_animations/14/8351.png")],
    //     [@image-url("assets/char_animations/15/8352.png"), @image-url("assets/char_animations/15/8353.png"), @image-url("assets/char_animations/15/8354.png"), @image-url("assets/char_animations/15/8355.png"), @image-url("assets/char_animations/15/8356.png"), @image-url("assets/char_animations/15/8357.png"), @image-url("assets/char_animations/15/8358.png"), @image-url("assets/char_animations/15/8359.png"), @image-url("assets/char_animations/15/8360.png"), @image-url("assets/char_animations/15/8361.png"), @image-url("assets/char_animations/15/8362.png"), @image-url("assets/char_animations/15/8363.png")],
    //     [@image-url("assets/char_animations/16/8364.png"), @image-url("assets/char_animations/16/8365.png"), @image-url("assets/char_animations/16/8366.png"), @image-url("assets/char_animations/16/8367.png"), @image-url("assets/char_animations/16/8368.png"), @image-url("assets/char_animations/16/8369.png"), @image-url("assets/char_animations/16/8370.png"), @image-url("assets/char_animations/16/8371.png"), @image-url("assets/char_animations/16/8372.png"), @image-url("assets/char_animations/16/8373.png"), @image-url("assets/char_animations/16/8374.png")],
    //     [@image-url("assets/char_animations/17/8375.png"), @image-url("assets/char_animations/17/8376.png"), @image-url("assets/char_animations/17/8377.png"), @image-url("assets/char_animations/17/8378.png"), @image-url("assets/char_animations/17/8379.png"), @image-url("assets/char_animations/17/8380.png"), @image-url("assets/char_animations/17/8381.png"), @image-url("assets/char_animations/17/8382.png"), @image-url("assets/char_animations/17/8383.png"), @image-url("assets/char_animations/17/8384.png")],
    //     [@image-url("assets/char_animations/18/8385.png"), @image-url("assets/char_animations/18/8386.png"), @image-url("assets/char_animations/18/8387.png"), @image-url("assets/char_animations/18/8388.png"), @image-url("assets/char_animations/18/8389.png"), @image-url("assets/char_animations/18/8390.png"), @image-url("assets/char_animations/18/8391.png"), @image-url("assets/char_animations/18/8392.png"), @image-url("assets/char_animations/18/8393.png"), @image-url("assets/char_animations/18/8394.png")],
    //     [@image-url("assets/char_animations/19/8395.png"), @image-url("assets/char_animations/19/8396.png"), @image-url("assets/char_animations/19/8397.png"), @image-url("assets/char_animations/19/8398.png"), @image-url("assets/char_animations/19/8399.png"), @image-url("assets/char_animations/19/8400.png"), @image-url("assets/char_animations/19/8401.png"), @image-url("assets/char_animations/19/8402.png"), @image-url("assets/char_animations/19/8403.png"), @image-url("assets/char_animations/19/8404.png")],
    //     [@image-url("assets/char_animations/20/8405.png"), @image-url("assets/char_animations/20/8406.png"), @image-url("assets/char_animations/20/8407.png"), @image-url("assets/char_animations/20/8408.png"), @image-url("assets/char_animations/20/8409.png"), @image-url("assets/char_animations/20/8410.png"), @image-url("assets/char_animations/20/8411.png"), @image-url("assets/char_animations/20/8412.png"), @image-url("assets/char_animations/20/8413.png"), @image-url("assets/char_animations/20/8414.png")],
    //     [@image-url("assets/char_animations/21/8415.png"), @image-url("assets/char_animations/21/8416.png"), @image-url("assets/char_animations/21/8417.png"), @image-url("assets/char_animations/21/8418.png"), @image-url("assets/char_animations/21/8419.png"), @image-url("assets/char_animations/21/8420.png"), @image-url("assets/char_animations/21/8421.png"), @image-url("assets/char_animations/21/8422.png"), @image-url("assets/char_animations/21/8423.png"), @image-url("assets/char_animations/21/8424.png")],
    //     [@image-url("assets/char_animations/22/8425.png"), @image-url("assets/char_animations/22/8426.png"), @image-url("assets/char_animations/22/8427.png"), @image-url("assets/char_animations/22/8428.png"), @image-url("assets/char_animations/22/8429.png"), @image-url("assets/char_animations/22/8430.png"), @image-url("assets/char_animations/22/8431.png"), @image-url("assets/char_animations/22/8432.png"), @image-url("assets/char_animations/22/8433.png"), @image-url("assets/char_animations/22/8434.png")],
    //     [@image-url("assets/char_animations/23/8435.png"), @image-url("assets/char_animations/23/8436.png"), @image-url("assets/char_animations/23/8437.png"), @image-url("assets/char_animations/23/8438.png"), @image-url("assets/char_animations/23/8439.png"), @image-url("assets/char_animations/23/8440.png"), @image-url("assets/char_animations/23/8441.png"), @image-url("assets/char_animations/23/8442.png"), @image-url("assets/char_animations/23/8443.png"), @image-url("assets/char_animations/23/8444.png")],
    //     [@image-url("assets/char_animations/24/8445.png"), @image-url("assets/char_animations/24/8446.png"), @image-url("assets/char_animations/24/8447.png"), @image-url("assets/char_animations/24/8448.png"), @image-url("assets/char_animations/24/8449.png"), @image-url("assets/char_animations/24/8450.png"), @image-url("assets/char_animations/24/8451.png"), @image-url("assets/char_animations/24/8452.png"), @image-url("assets/char_animations/24/8453.png"), @image-url("assets/char_animations/24/8454.png")],
    //     [@image-url("assets/char_animations/25/8455.png"), @image-url("assets/char_animations/25/8456.png"), @image-url("assets/char_animations/25/8457.png"), @image-url("assets/char_animations/25/8458.png"), @image-url("assets/char_animations/25/8459.png"), @image-url("assets/char_animations/25/8460.png"), @image-url("assets/char_animations/25/8461.png"), @image-url("assets/char_animations/25/8462.png"), @image-url("assets/char_animations/25/8463.png"), @image-url("assets/char_animations/25/8464.png"), @image-url("assets/char_animations/25/8465.png")],
    //     [@image-url("assets/char_animations/26/8466.png"), @image-url("assets/char_animations/26/8467.png"), @image-url("assets/char_animations/26/8468.png"), @image-url("assets/char_animations/26/8469.png"), @image-url("assets/char_animations/26/8470.png"), @image-url("assets/char_animations/26/8471.png"), @image-url("assets/char_animations/26/8472.png"), @image-url("assets/char_animations/26/8473.png"), @image-url("assets/char_animations/26/8474.png"), @image-url("assets/char_animations/26/8475.png"), @image-url("assets/char_animations/26/8476.png")],
    //     [@image-url("assets/char_animations/27/8477.png"), @image-url("assets/char_animations/27/8478.png"), @image-url("assets/char_animations/27/8479.png"), @image-url("assets/char_animations/27/8480.png"), @image-url("assets/char_animations/27/8481.png"), @image-url("assets/char_animations/27/8482.png"), @image-url("assets/char_animations/27/8483.png"), @image-url("assets/char_animations/27/8484.png"), @image-url("assets/char_animations/27/8485.png"), @image-url("assets/char_animations/27/8486.png"), @image-url("assets/char_animations/27/8487.png")],
    //     [@image-url("assets/char_animations/28/8488.png"), @image-url("assets/char_animations/28/8489.png"), @image-url("assets/char_animations/28/8490.png"), @image-url("assets/char_animations/28/8491.png"), @image-url("assets/char_animations/28/8492.png"), @image-url("assets/char_animations/28/8493.png"), @image-url("assets/char_animations/28/8494.png"), @image-url("assets/char_animations/28/8495.png"), @image-url("assets/char_animations/28/8496.png"), @image-url("assets/char_animations/28/8497.png"), @image-url("assets/char_animations/28/8498.png")],
    //     [@image-url("assets/char_animations/29/8499.png"), @image-url("assets/char_animations/29/8500.png"), @image-url("assets/char_animations/29/8501.png"), @image-url("assets/char_animations/29/8502.png"), @image-url("assets/char_animations/29/8503.png"), @image-url("assets/char_animations/29/8504.png"), @image-url("assets/char_animations/29/8505.png"), @image-url("assets/char_animations/29/8506.png"), @image-url("assets/char_animations/29/8507.png"), @image-url("assets/char_animations/29/8508.png")],
    //     [@image-url("assets/char_animations/30/8509.png"), @image-url("assets/char_animations/30/8510.png"), @image-url("assets/char_animations/30/8511.png"), @image-url("assets/char_animations/30/8512.png"), @image-url("assets/char_animations/30/8513.png"), @image-url("assets/char_animations/30/8514.png"), @image-url("assets/char_animations/30/8515.png"), @image-url("assets/char_animations/30/8516.png"), @image-url("assets/char_animations/30/8517.png"), @image-url("assets/char_animations/30/8518.png")],
    //     [@image-url("assets/char_animations/31/8519.png"), @image-url("assets/char_animations/31/8520.png"), @image-url("assets/char_animations/31/8521.png"), @image-url("assets/char_animations/31/8522.png"), @image-url("assets/char_animations/31/8523.png"), @image-url("assets/char_animations/31/8524.png"), @image-url("assets/char_animations/31/8525.png"), @image-url("assets/char_animations/31/8526.png"), @image-url("assets/char_animations/31/8527.png"), @image-url("assets/char_animations/31/8528.png")],
    //     [@image-url("assets/char_animations/32/8529.png"), @image-url("assets/char_animations/32/8530.png"), @image-url("assets/char_animations/32/8531.png"), @image-url("assets/char_animations/32/8532.png"), @image-url("assets/char_animations/32/8533.png"), @image-url("assets/char_animations/32/8534.png"), @image-url("assets/char_animations/32/8535.png"), @image-url("assets/char_animations/32/8536.png"), @image-url("assets/char_animations/32/8537.png"), @image-url("assets/char_animations/32/8538.png"), @image-url("assets/char_animations/32/8539.png"), @image-url("assets/char_animations/32/8540.png")],
    //     [@image-url("assets/char_animations/33/8541.png"), @image-url("assets/char_animations/33/8542.png"), @image-url("assets/char_animations/33/8543.png"), @image-url("assets/char_animations/33/8544.png"), @image-url("assets/char_animations/33/8545.png"), @image-url("assets/char_animations/33/8546.png"), @image-url("assets/char_animations/33/8547.png"), @image-url("assets/char_animations/33/8548.png"), @image-url("assets/char_animations/33/8549.png"), @image-url("assets/char_animations/33/8550.png"), @image-url("assets/char_animations/33/8551.png"), @image-url("assets/char_animations/33/8552.png")],
    //     [@image-url("assets/char_animations/34/8553.png"), @image-url("assets/char_animations/34/8554.png"), @image-url("assets/char_animations/34/8555.png"), @image-url("assets/char_animations/34/8556.png"), @image-url("assets/char_animations/34/8557.png")],
    //     [@image-url("assets/char_animations/35/8558.png"), @image-url("assets/char_animations/35/8559.png"), @image-url("assets/char_animations/35/8560.png"), @image-url("assets/char_animations/35/8561.png"), @image-url("assets/char_animations/35/8562.png"), @image-url("assets/char_animations/35/8563.png"), @image-url("assets/char_animations/35/8564.png"), @image-url("assets/char_animations/35/8565.png"), @image-url("assets/char_animations/35/8566.png"), @image-url("assets/char_animations/35/8567.png"), @image-url("assets/char_animations/35/8568.png")],
    //     [@image-url("assets/char_animations/36/8569.png"), @image-url("assets/char_animations/36/8570.png"), @image-url("assets/char_animations/36/8571.png"), @image-url("assets/char_animations/36/8572.png"), @image-url("assets/char_animations/36/8573.png"), @image-url("assets/char_animations/36/8574.png"), @image-url("assets/char_animations/36/8575.png"), @image-url("assets/char_animations/36/8576.png"), @image-url("assets/char_animations/36/8577.png"), @image-url("assets/char_animations/36/8578.png"), @image-url("assets/char_animations/36/8579.png"), @image-url("assets/char_animations/36/8580.png")],
    //     [@image-url("assets/char_animations/37/8581.png"), @image-url("assets/char_animations/37/8582.png"), @image-url("assets/char_animations/37/8583.png"), @image-url("assets/char_animations/37/8584.png"), @image-url("assets/char_animations/37/8585.png"), @image-url("assets/char_animations/37/8586.png"), @image-url("assets/char_animations/37/8587.png"), @image-url("assets/char_animations/37/8588.png"), @image-url("assets/char_animations/37/8589.png"), @image-url("assets/char_animations/37/8590.png"), @image-url("assets/char_animations/37/8591.png"), @image-url("assets/char_animations/37/8592.png")],
    //     [@image-url("assets/char_animations/38/8593.png"), @image-url("assets/char_animations/38/8594.png"), @image-url("assets/char_animations/38/8595.png"), @image-url("assets/char_animations/38/8596.png"), @image-url("assets/char_animations/38/8597.png"), @image-url("assets/char_animations/38/8598.png"), @image-url("assets/char_animations/38/8599.png"), @image-url("assets/char_animations/38/8600.png"), @image-url("assets/char_animations/38/8601.png"), @image-url("assets/char_animations/38/8602.png"), @image-url("assets/char_animations/38/8603.png"), @image-url("assets/char_animations/38/8604.png")],
    //     [@image-url("assets/char_animations/39/8962.png"), @image-url("assets/char_animations/39/8963.png"), @image-url("assets/char_animations/39/8964.png"), @image-url("assets/char_animations/39/8965.png"), @image-url("assets/char_animations/39/8966.png"), @image-url("assets/char_animations/39/8967.png"), @image-url("assets/char_animations/39/8968.png"), @image-url("assets/char_animations/39/8969.png"), @image-url("assets/char_animations/39/8970.png"), @image-url("assets/char_animations/39/8971.png")],
    //     [@image-url("assets/char_animations/40/8615.png"), @image-url("assets/char_animations/40/8616.png"), @image-url("assets/char_animations/40/8617.png"), @image-url("assets/char_animations/40/8618.png"), @image-url("assets/char_animations/40/8619.png"), @image-url("assets/char_animations/40/8620.png"), @image-url("assets/char_animations/40/8621.png"), @image-url("assets/char_animations/40/8622.png"), @image-url("assets/char_animations/40/8623.png"), @image-url("assets/char_animations/40/8624.png"), @image-url("assets/char_animations/40/8625.png"), @image-url("assets/char_animations/40/8626.png")],
    //     [@image-url("assets/char_animations/41/8628.png"), @image-url("assets/char_animations/41/8629.png"), @image-url("assets/char_animations/41/8630.png"), @image-url("assets/char_animations/41/8631.png"), @image-url("assets/char_animations/41/8632.png"), @image-url("assets/char_animations/41/8633.png"), @image-url("assets/char_animations/41/8634.png"), @image-url("assets/char_animations/41/8635.png"), @image-url("assets/char_animations/41/8636.png"), @image-url("assets/char_animations/41/8637.png"), @image-url("assets/char_animations/41/8638.png")],
    //     [@image-url("assets/char_animations/42/8639.png"), @image-url("assets/char_animations/42/8640.png"), @image-url("assets/char_animations/42/8641.png"), @image-url("assets/char_animations/42/8642.png"), @image-url("assets/char_animations/42/8643.png"), @image-url("assets/char_animations/42/8644.png"), @image-url("assets/char_animations/42/8645.png"), @image-url("assets/char_animations/42/8646.png"), @image-url("assets/char_animations/42/8647.png"), @image-url("assets/char_animations/42/8648.png"), @image-url("assets/char_animations/42/8649.png")],
    //     [@image-url("assets/char_animations/43/8650.png"), @image-url("assets/char_animations/43/8651.png"), @image-url("assets/char_animations/43/8652.png"), @image-url("assets/char_animations/43/8653.png"), @image-url("assets/char_animations/43/8654.png"), @image-url("assets/char_animations/43/8655.png"), @image-url("assets/char_animations/43/8656.png"), @image-url("assets/char_animations/43/8657.png"), @image-url("assets/char_animations/43/8658.png"), @image-url("assets/char_animations/43/8659.png")],
    //     [@image-url("assets/char_animations/44/8660.png"), @image-url("assets/char_animations/44/8661.png"), @image-url("assets/char_animations/44/8662.png"), @image-url("assets/char_animations/44/8663.png"), @image-url("assets/char_animations/44/8664.png"), @image-url("assets/char_animations/44/8665.png"), @image-url("assets/char_animations/44/8666.png"), @image-url("assets/char_animations/44/8667.png"), @image-url("assets/char_animations/44/8668.png"), @image-url("assets/char_animations/44/8669.png")],
    //     [@image-url("assets/char_animations/45/8670.png"), @image-url("assets/char_animations/45/8671.png"), @image-url("assets/char_animations/45/8672.png"), @image-url("assets/char_animations/45/8673.png"), @image-url("assets/char_animations/45/8674.png"), @image-url("assets/char_animations/45/8675.png"), @image-url("assets/char_animations/45/8676.png"), @image-url("assets/char_animations/45/8677.png"), @image-url("assets/char_animations/45/8678.png"), @image-url("assets/char_animations/45/8679.png")],
    //     [@image-url("assets/char_animations/46/8680.png"), @image-url("assets/char_animations/46/8681.png"), @image-url("assets/char_animations/46/8682.png"), @image-url("assets/char_animations/46/8683.png"), @image-url("assets/char_animations/46/8684.png"), @image-url("assets/char_animations/46/8685.png"), @image-url("assets/char_animations/46/8686.png"), @image-url("assets/char_animations/46/8687.png"), @image-url("assets/char_animations/46/8688.png"), @image-url("assets/char_animations/46/8689.png")],
    //     [@image-url("assets/char_animations/47/9047.png"), @image-url("assets/char_animations/47/9048.png"), @image-url("assets/char_animations/47/9049.png"), @image-url("assets/char_animations/47/9050.png"), @image-url("assets/char_animations/47/9051.png"), @image-url("assets/char_animations/47/9052.png"), @image-url("assets/char_animations/47/9053.png"), @image-url("assets/char_animations/47/9054.png"), @image-url("assets/char_animations/47/9055.png"), @image-url("assets/char_animations/47/9056.png")],
    //     [@image-url("assets/char_animations/48/8700.png"), @image-url("assets/char_animations/48/8701.png")],
    //     [@image-url("assets/char_animations/49/9073.png"), @image-url("assets/char_animations/49/9074.png"), @image-url("assets/char_animations/49/9075.png"), @image-url("assets/char_animations/49/9076.png"), @image-url("assets/char_animations/49/9077.png"), @image-url("assets/char_animations/49/9078.png"), @image-url("assets/char_animations/49/9079.png"), @image-url("assets/char_animations/49/9080.png"), @image-url("assets/char_animations/49/9081.png"), @image-url("assets/char_animations/49/9082.png")],
    //     [@image-url("assets/char_animations/50/9119.png"), @image-url("assets/char_animations/50/9120.png"), @image-url("assets/char_animations/50/9121.png"), @image-url("assets/char_animations/50/9122.png"), @image-url("assets/char_animations/50/9123.png"), @image-url("assets/char_animations/50/9124.png"), @image-url("assets/char_animations/50/9125.png"), @image-url("assets/char_animations/50/9126.png"), @image-url("assets/char_animations/50/9127.png"), @image-url("assets/char_animations/50/9128.png"), @image-url("assets/char_animations/50/9129.png")],
    //     [@image-url("assets/char_animations/51/9132.png"), @image-url("assets/char_animations/51/9133.png"), @image-url("assets/char_animations/51/9134.png"), @image-url("assets/char_animations/51/9135.png"), @image-url("assets/char_animations/51/9136.png"), @image-url("assets/char_animations/51/9137.png"), @image-url("assets/char_animations/51/9138.png"), @image-url("assets/char_animations/51/9139.png"), @image-url("assets/char_animations/51/9140.png"), @image-url("assets/char_animations/51/9141.png")],
    //     [@image-url("assets/char_animations/52/9156.png"), @image-url("assets/char_animations/52/9157.png"), @image-url("assets/char_animations/52/9158.png"), @image-url("assets/char_animations/52/9159.png"), @image-url("assets/char_animations/52/9160.png"), @image-url("assets/char_animations/52/9161.png"), @image-url("assets/char_animations/52/9162.png"), @image-url("assets/char_animations/52/9163.png"), @image-url("assets/char_animations/52/9164.png"), @image-url("assets/char_animations/52/9165.png"), @image-url("assets/char_animations/52/9166.png")],
    //     [@image-url("assets/char_animations/53/9167.png"), @image-url("assets/char_animations/53/9168.png"), @image-url("assets/char_animations/53/9169.png"), @image-url("assets/char_animations/53/9170.png"), @image-url("assets/char_animations/53/9171.png"), @image-url("assets/char_animations/53/9172.png"), @image-url("assets/char_animations/53/9173.png"), @image-url("assets/char_animations/53/9174.png"), @image-url("assets/char_animations/53/9175.png"), @image-url("assets/char_animations/53/9176.png"), @image-url("assets/char_animations/53/9177.png"), @image-url("assets/char_animations/53/9178.png")],
    //     [@image-url("assets/char_animations/54/9191.png"), @image-url("assets/char_animations/54/9192.png"), @image-url("assets/char_animations/54/9193.png"), @image-url("assets/char_animations/54/9194.png"), @image-url("assets/char_animations/54/9195.png"), @image-url("assets/char_animations/54/9196.png"), @image-url("assets/char_animations/54/9197.png"), @image-url("assets/char_animations/54/9198.png"), @image-url("assets/char_animations/54/9199.png"), @image-url("assets/char_animations/54/9200.png"), @image-url("assets/char_animations/54/9201.png"), @image-url("assets/char_animations/54/9202.png")],
    //     [],
    //     [@image-url("assets/char_animations/56/7684.png"), @image-url("assets/char_animations/56/7685.png"), @image-url("assets/char_animations/56/7686.png"), @image-url("assets/char_animations/56/7687.png"), @image-url("assets/char_animations/56/7688.png"), @image-url("assets/char_animations/56/7689.png"), @image-url("assets/char_animations/56/7690.png"), @image-url("assets/char_animations/56/7691.png")],
    // ];
    in property <[[image]]> characters-frames;
    property <[image]> avatars: [
        @image-url("assets/avatars/1.png"),
        @image-url("assets/avatars/2.png"),
        @image-url("assets/avatars/3.png"),
        @image-url("assets/avatars/4.png"),
        @image-url("assets/avatars/5.png"),
        @image-url("assets/avatars/6.png"),
        @image-url("assets/avatars/7.png"),
        @image-url("assets/avatars/8.png"),
        @image-url("assets/avatars/9.png"),
        @image-url("assets/avatars/10.png"),
        @image-url("assets/avatars/11.png"),
        @image-url("assets/avatars/12.png"),
        @image-url("assets/avatars/13.png"),
        @image-url("assets/avatars/14.png"),
        @image-url("assets/avatars/15.png"),
        @image-url("assets/avatars/16.png"),
        @image-url("assets/avatars/17.png"),
        @image-url("assets/avatars/18.png"),
        @image-url("assets/avatars/19.png"),
        @image-url("assets/avatars/20.png"),
        @image-url("assets/avatars/21.png"),
        @image-url("assets/avatars/22.png"),
        @image-url("assets/avatars/23.png"),
        @image-url("assets/avatars/24.png"),
        @image-url("assets/avatars/25.png"),
        @image-url("assets/avatars/26.png"),
        @image-url("assets/avatars/27.png"),
        @image-url("assets/avatars/28.png"),
        @image-url("assets/avatars/29.png"),
        @image-url("assets/avatars/30.png"),
        @image-url("assets/avatars/31.png"),
        @image-url("assets/avatars/32.png"),
        @image-url("assets/avatars/33.png"),
        @image-url("assets/avatars/34.png"),
        @image-url("assets/avatars/35.png"),
        @image-url("assets/avatars/36.png"),
        @image-url("assets/avatars/37.png"),
        @image-url("assets/avatars/38.png"),
        @image-url("assets/avatars/39.png"),
        @image-url("assets/avatars/40.png"),
        @image-url("assets/avatars/41.png"),
        @image-url("assets/avatars/42.png"),
        @image-url("assets/avatars/43.png"),
        @image-url("assets/avatars/44.png"),
        @image-url("assets/avatars/45.png"),
        @image-url("assets/avatars/46.png"),
        @image-url("assets/avatars/47.png"),
        @image-url("assets/avatars/48.png"),
    ];
    property <[image]> avatars_gray: [
        @image-url("assets/avatars_gray/1.png"),
        @image-url("assets/avatars_gray/2.png"),
        @image-url("assets/avatars_gray/3.png"),
        @image-url("assets/avatars_gray/4.png"),
        @image-url("assets/avatars_gray/5.png"),
        @image-url("assets/avatars_gray/6.png"),
        @image-url("assets/avatars_gray/7.png"),
        @image-url("assets/avatars_gray/8.png"),
        @image-url("assets/avatars_gray/9.png"),
        @image-url("assets/avatars_gray/10.png"),
        @image-url("assets/avatars_gray/11.png"),
        @image-url("assets/avatars_gray/12.png"),
        @image-url("assets/avatars_gray/13.png"),
        @image-url("assets/avatars_gray/14.png"),
        @image-url("assets/avatars_gray/15.png"),
        @image-url("assets/avatars_gray/16.png"),
        @image-url("assets/avatars_gray/17.png"),
        @image-url("assets/avatars_gray/18.png"),
        @image-url("assets/avatars_gray/19.png"),
        @image-url("assets/avatars_gray/20.png"),
        @image-url("assets/avatars_gray/21.png"),
        @image-url("assets/avatars_gray/22.png"),
        @image-url("assets/avatars_gray/23.png"),
        @image-url("assets/avatars_gray/24.png"),
        @image-url("assets/avatars_gray/25.png"),
        @image-url("assets/avatars_gray/26.png"),
        @image-url("assets/avatars_gray/27.png"),
        @image-url("assets/avatars_gray/28.png"),
        @image-url("assets/avatars_gray/29.png"),
        @image-url("assets/avatars_gray/30.png"),
        @image-url("assets/avatars_gray/31.png"),
        @image-url("assets/avatars_gray/32.png"),
        @image-url("assets/avatars_gray/33.png"),
        @image-url("assets/avatars_gray/34.png"),
        @image-url("assets/avatars_gray/35.png"),
        @image-url("assets/avatars_gray/36.png"),
        @image-url("assets/avatars_gray/37.png"),
        @image-url("assets/avatars_gray/38.png"),
        @image-url("assets/avatars_gray/39.png"),
        @image-url("assets/avatars_gray/40.png"),
        @image-url("assets/avatars_gray/41.png"),
        @image-url("assets/avatars_gray/42.png"),
        @image-url("assets/avatars_gray/43.png"),
        @image-url("assets/avatars_gray/44.png"),
        @image-url("assets/avatars_gray/45.png"),
        @image-url("assets/avatars_gray/46.png"),
        @image-url("assets/avatars_gray/47.png"),
        @image-url("assets/avatars_gray/48.png"),
    ];
    property <[string]> names: [
        "Freddy",
        "Bonnie",
        "Chica",
        "Foxy",
        "Toy Bonnie",
        "Toy Chica",
        "Toy Freddy",
        "Mangle",
        "BB",
        "JJ",
        "Phantom Freddy",
        "Phantom Chica",
        "Phantom BB",
        "Phantom Foxy",
        "Phantom Mangle",
        "Withered Bonnie",
        "Withered Chica",
        "Withered Freddy",
        "Withered Foxy",
        "Shadow Freddy",
        "Marionette",
        "Phantom Marionette",
        "Golden Freddy",
        "Paperpals",
        "Nightmare Freddy",
        "Nightmare Bonnie",
        "Nightmare Chica",
        "Nightmare Foxy",
        "Endo-01",
        "Endo-02",
        "Plushtrap",
        "Endoplush",
        "Springtrap",
        "RWQFSXQC", // TODO: Check actual name
        "Crying Child",
        "Funtime Foxy",
        "Nightmare Freadbear",
        "Nightmare",
        "Freadbear",
        "Spring Bonnie",
        "Jack-o-Bonnie",
        "Jack-o-Chica",
        "Animdude",
        "Chipper",
        "Nightmare BB",
        "Nightmarrione",
        "Coffee",
        "Purple Guy",
    ];

    in-out property <[Character]> char-data: [
        {lvl: 5, next: 296},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
        {lvl: 1, next: 100},
    ];

    public function show(id: int) {
        id-show = id;
        lvl-field.value = char-data[id - 1].lvl;
        next-field.value = char-data[id - 1].next;
    }

    public function select(id: int) {
        id-selected = id;
        show(id)
    }

    property <int> id-selected: 0;
    property <int> id-show: id-selected;

    callback lvl-edited(int, int);
    callback next-edited(int, int);
    callback have-edited(int);

    ta := TouchArea {
        pointer-event(event) => {
            if event.kind == PointerEventKind.move && root.id-selected == 0 {
                show(0);
            }
        }
        clicked => {
            select(0);
        }
    }

    HorizontalLayout {
        padding: 5px;
        VerticalLayout {
            width: 600px;

            Text {
                text: "Party";
                font-size: 28px;
                horizontal-alignment: center;
                vertical-alignment: center;
            }
            table-layout := VerticalLayout {
                alignment: LayoutAlignment.start;
                spacing: 2px;
                for j in 6: row := HorizontalLayout {
                    alignment: start;
                    spacing: 2px;
                    for i in 8: Avatar {
                        id: 8 * j + i + 1;
                        avatar: avatars[8 * j + i];
                        avatar-gray: avatars_gray[8 * j + i];
                        selected-id: root.id-selected;
                        activated: root.char-data[8 * j + i].activated;
                        select(id) => {
                            if self.activated {
                                if root.id-selected != id {
                                    select(id)
                                }
                                else {
                                    select(0)
                                }
                            }
                            else {
                                select(0)
                            }
                        }
                        enter(id) => {
                            if root.id-selected == 0 && self.activated {
                                show(id)
                            }
                            if root.id-selected == 0 && !self.activated {
                                show(0)
                            }
                        }
                        change-state(id) => {
                            root.have-edited(id);
                            root.char-data[8 * j + i].activated = !root.char-data[8 * j + i].activated;
                            if !root.char-data[8 * j + i].activated {
                                root.char-data[id - 1] = {lvl: 1, next: 100};
                                select(0)
                            }
                        }
                    }
                }
            }
            Text {
                text: "Double click to add or remove from save. Click to select to edit properties";
                horizontal-alignment: center;
            }
        }

        VerticalLayout {
            visible: id-show == 0 ? false : true;
            // opacity: id-show == 0 ? 0.5 : 1.0;
            spacing: 15px;
            alignment: LayoutAlignment.center;

            Text {
                text: names[id-show - 1];
                horizontal-alignment: center;
                vertical-alignment: center;
                font-size: 20px;
            }

            ImageAnim {
                frames: characters-frames[id-show];
            }

            HorizontalLayout {
                spacing: 5px;

                Text {
                    text: "Level: ";
                    vertical-alignment: center;
                }
                lvl-field := SpinBox {
                    minimum: 1;
                    maximum: 999999;
                    edited(value) => {
                        char-data[root.id-selected - 1].lvl = value;
                        lvl-edited(id-selected, value - 1);
                    }
                }
            }
            HorizontalLayout {
                spacing: 5px;

                Text {
                    text: "Exp to next: ";
                    vertical-alignment: center;
                }
                next-field := SpinBox {
                    minimum: 1;
                    maximum: 999999;
                    edited(value) => {
                        char-data[root.id-selected - 1].next = value;
                        next-edited(id-selected, value - 1)
                    }
                }
            }
        }
    }
}